Added service account page
Axway/axwaycli-open-docs pull request #22
Opened 2021-08-31 13:48 UTC by cb1kenobi

JIRA: https://jira.axway.com/browse/APIGOV-20266

2021-08-31 16:14 UTC, sallylanda6 requested changes
I am recommending some copy edit changes for consistency and to use active instead of passive voice.

2021-08-31 16:23 UTC, cb1kenobi commented on content/en/docs/authentication/service_accounts.md
> +The client id defaults to the specified service account name plus a uuid. You can override this an specify your own client id, however the client id cannot begin with "AASA", "CASA", "DOSA", or "MASA
Not sure I agree. The sentence has been negated and thus the negation of "and" is "or". Just want to confirm, should this definitely be "and"?

2021-08-31 16:26 UTC, cb1kenobi commented on content/en/docs/authentication/service_accounts.md
> +The client id defaults to the specified service account name plus a uuid. You can override this an specify your own client id, however the client id cannot begin with "AASA", "CASA", "DOSA", or "MASA
These are very specific values and I don't want to confused "MASA" with "MASA.". I've made each of these keywords code blocks.

2021-08-31 16:46 UTC, sallylanda6 commented on content/en/docs/authentication/service_accounts.md
> +The client id defaults to the specified service account name plus a uuid. You can override this an specify your own client id, however the client id cannot begin with "AASA", "CASA", "DOSA", or "MASA
Not sure what your comment refers to. This is where I was saying to change an to and... "You can override this an specify your own client id". I thought inline comments would highlight the exact area but I guess it does not and I need to be more specific.

This sentence "If prompting is not available, then all required options must passed in at execution" the word "be" is missing. "If prompting is not available, then all required options must be passed in at execution."

2021-08-31 16:46 UTC, sallylanda6 commented on content/en/docs/authentication/service_accounts.md
> +The client id defaults to the specified service account name plus a uuid. You can override this an specify your own client id, however the client id cannot begin with "AASA", "CASA", "DOSA", or "MASA
Perfect!

2021-08-31 16:51 UTC, cb1kenobi commented on content/en/docs/authentication/service_accounts.md
> +The client id defaults to the specified service account name plus a uuid. You can override this an specify your own client id, however the client id cannot begin with "AASA", "CASA", "DOSA", or "MASA
OH! "an"!!!

2021-08-31 21:40 UTC, sallylanda6 requested changes
Sorry, I missed one. I think this is all.

2021-08-31 21:40 UTC, sallylanda6 commented on content/en/docs/authentication/service_accounts.md
> +You may specify the service account by client id or name as well as the team by guid or name. The available team roles can be discovered by running `axway service-account roles`.
I missed one... change to 
Run `axway service-account roles` to discover the available team roles.

2021-09-01 16:10 UTC, sallylanda6 approved these changes
Looks good!

2021-09-24 21:05 UTC, merged